configurationVariables:
  jdbcfunc.SAPTxStore.failFastMode: 'false'
  jdbcfunc.SAPTxStore.connPoolAlias: SAP TxStore Pool
info:
  model: int-scaffold
packages:
- gitBranch: release/1.7.2
  gitServerName: moaa
  gitUrl: https://github.com/Mohamed-Naufal-A-IBM
  gitUsername: Mohamed-Naufal-A-IBM
  name: TestVersioningProject
version: 1.7.2
